name: cldphase
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tensorflow=2.15.0
  - scikit-learn=1.3.0
  - netCDF4=1.6.5
  - xarray[accel,parallel]=2024.1.1
  - scipy=1.12.0
  - pandas=1.5.3
  - numpy=1.26.3
  - pyarrow=15.0.0
  - matplotlib=3.8.2
  - plotly=5.18.0
  - tqdm=4.66.1
  - act-atmos=2.1.3
  - jupyter
  - notebook
  - pip
  - pip:
    - kaleido==0.2.1
